# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: stefco/hpmoc-env:latest
image: continuumio/miniconda3:latest

definitions:
  steps:
    - step: &build-test
        name: Build and test
        caches:
          - pip
        script:
          - pip install flit
          - FLIT_ROOT_INSTALL=1 flit install --symlink
          - py.test --doctest-modules --cov=hpmoc
          - flit build
        artifacts:
          - dist/*whl
    - step: &bitbucket-wheel-upload
        name: Upload latest wheel to Bitbucket
        script:
          - |
            mv dist/hpmoc-$BITBUCKET_TAG-py3-none-any.whl \
               dist/hpmoc-latest-py3-none-any.whl
          - pipe: atlassian/bitbucket-upload-file:0.1.8
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              FILENAME: dist/hpmoc-latest-py3-none-any.whl
              # ACCOUNT: stefancountryman
              # REPOSITORY: multimessenger-pipeline
    - step: &build-upload-docker
        name: Build/upload Docker image
        services:
          - docker
        caches:
          - pip
          - docker
        script:
          - |
            mv dist/hpmoc-$BITBUCKET_TAG-py3-none-any.whl \
               dist/hpmoc-latest-py3-none-any.whl
          - ls -la dist  # TODO REMOVE
          - chmod 666 dist/hpmoc-latest-py3-none-any.whl
          - ls -la dist  # TODO REMOVE
          - docker build -t stefco/llama:hpmoc .
          - docker push stefco/llama:hpmoc
          - docker tag stefco/llama:hpmoc stefco/llama:hpmoc-$BITBUCKET_TAG
          - docker push stefco/llama:hpmoc-$BITBUCKET_TAG

pipelines:
  default:
    - step: *build-test
    - step:
        name: Upload latest wheel to Bitbucket
        script:
          - ls -la dist  # TODO REMOVE
          - |
            mv dist/hpmoc-*-py3-none-any.whl \
               dist/hpmoc-latest-py3-none-any.whl
          - ls -la dist  # TODO REMOVE
          - apt-get install -y install curl
          # - |
          #   curl -X POST \
          #     https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG/downloads \
          #     --form files=@"/dist/py_llama-*-py3-none-any.whl"
          - pipe: atlassian/bitbucket-upload-file:0.1.8
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
              FILENAME: dist/hpmoc-latest-py3-none-any.whl
              # ACCOUNT: stefancountryman
              # REPOSITORY: multimessenger-pipeline
  tags:
    v*:
      - step: *build-test
      - parallel:
          - step: *bitbucket-wheel-upload
          - step: *build-upload-docker
